-- Seed: 002_seed_products.sql
-- Description: Seed products data

BEGIN;

INSERT INTO products (sku, name, slug, description, short_description, category_id, status, price, compare_at_price, cost_price, stock_quantity, low_stock_threshold, weight_kg, dimensions_cm, brand, manufacturer, is_featured, rating_average, rating_count, created_at, updated_at)
VALUES
    (
        'LAP001',
        'MacBook Pro 14"',
        'macbook-pro-14',
        'High-performance laptop for professionals',
        'M3 Pro Chip, 16GB RAM, 512GB SSD',
        2,
        'active',
        1999.99,
        2399.99,
        1200.00,
        50,
        10,
        1.6,
        '31x22x1.6',
        'Apple',
        'Apple Inc.',
        true,
        4.8,
        245,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'LAP002',
        'Dell XPS 13',
        'dell-xps-13',
        'Compact ultrabook with stunning display',
        'Intel Core i7, 16GB RAM, 512GB SSD',
        2,
        'active',
        1299.99,
        1499.99,
        800.00,
        35,
        10,
        1.3,
        '29.7x21.5x1.5',
        'Dell',
        'Dell Technologies',
        true,
        4.6,
        189,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'ACC001',
        'USB-C Hub',
        'usb-c-hub',
        '7-in-1 USB-C hub with multiple ports',
        'HDMI, USB 3.0, SD Card, USB-C',
        3,
        'active',
        49.99,
        69.99,
        25.00,
        200,
        30,
        0.15,
        NULL,
        'TechMax',
        'TechMax Industries',
        false,
        4.5,
        342,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'ACC002',
        'Wireless Mouse',
        'wireless-mouse',
        'Ergonomic wireless mouse with silent clicks',
        '2.4GHz, 18-month battery life',
        3,
        'active',
        29.99,
        39.99,
        12.00,
        150,
        30,
        0.1,
        NULL,
        'Logitech',
        'Logitech International',
        false,
        4.7,
        521,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'BOOK001',
        'The Go Programming Language',
        'go-programming-language',
        'Official guide to Go programming',
        'Learn Go from the creators',
        4,
        'active',
        59.99,
        NULL,
        30.00,
        100,
        20,
        0.8,
        NULL,
        'Addison-Wesley',
        'Pearson Education',
        false,
        4.9,
        1280,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'CLT001',
        'Cotton T-Shirt',
        'cotton-t-shirt',
        '100% organic cotton comfortable t-shirt',
        'Available in multiple sizes and colors',
        5,
        'active',
        24.99,
        34.99,
        10.00,
        500,
        100,
        0.2,
        NULL,
        'ComfortWear',
        'ComfortWear Ltd.',
        false,
        4.4,
        892,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT (sku) DO NOTHING;

COMMIT;
